# Generated by Django 5.1.5 on 2025-02-04 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Moderate'), ('D', 'Difficult')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('national_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='my_app.nationalpark')),
            ],
        ),
    ]
