# Generated by Django 5.1.5 on 2025-02-04 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_trail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Moderate'), ('D', 'Difficult')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='trail',
            name='national_park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.nationalpark'),
        ),
    ]
