# Generated by Django 5.1.6 on 2025-02-07 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_trail_options_nationalpark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='description',
        ),
    ]
